#!/bin/sh

fname=$1

if [ "$fname" != "" ]
then
	echo "folder is $fname"
	cp ./config.yaml ../data/webfiles/$fname/config.yaml
	/source/OpenSfM/bin/opensfm_run_all ../data/webfiles/$fname
	/source/OpenSfM/bin/opensfm undistort ../data/webfiles/$fname
	/source/OpenSfM/bin/opensfm compute_depthmaps ../data/webfiles/$fname
	cp ../data/webfiles/$fname/undistorted/depthmaps/merged.ply ../webroot/downloads/$fname.ply
else
	echo "Please supply a folder name to target"
fi
